### ISSUE TITLE
Update pip dependencies

### ISSUE THREAD

**Issue by grgmiller** [singularity-energy/open-grid-emissions#234]
The OGE pipeline depends on two external projects: `pudl` and `gridemissions`. However, our dependencies are currently to two forks that @gailin-p and I have made from the original code:
 - https://github.com/grgmiller/pudl.git@allocate_fuel
 - https://github.com/gailin-p/gridemissions

We should come up with a more permanent solution for this going forward. If we are going to continue working off of forks, we may want to fork these to the singularity-energy github account, instead of our personal acccounts.

With regards to the base repositories:
 - For PUDL: I think once the current updates in the dev branch of pudl (including the boiler fuel allocation improvements, once merged) are merged into main, we could point back to pudl@main. 
 - For gridemissions: I think our use of the base repo depends on how actively they want to maintain the base repository. If they are not interested in actively maintaining it going forward, we may want to adopt the repo and/or just start working off of a singularity fork. I don't think we necessarily want to create diverging versions of the same code, but we should work with them to figure that out.

**Comment by gailin-p** [comment]
The context for this issue was changed by #235, which points at an archived version of PUDL code (hosted on @grgmiller's github) and data (hosted on Zenodo). Because these archived versions require us to manually update them and then check our own code for compatibility whenever we want to incorporate new PUDL data, they are not ideal. 

However, we probably don't want to point directly at pudl@main until PUDL releases a 1.x version, because PUDL in 0.x changes data formats and breaks our code, and it's nice to have control over when we bring ourselves up to date with these changes (ie, by archiving our own version of PUDL, #235)

**Comment by grgmiller** [comment]
With v0.2.0, we now point directly to pudl@main for our pudl dependency.

**Comment by grgmiller** [comment]
Fixed by https://github.com/singularity-energy/open-grid-emissions/pull/327 and https://github.com/singularity-energy/open-grid-emissions/pull/318
