### ISSUE TITLE
Package the repository

### ISSUE THREAD

**Issue by grgmiller** [singularity-energy/open-grid-emissions#33]
Packaging `open-grid-emissions` will allow us (and others) to use code snippets in other projects.

## Specific tasks:
- [ ] Currently all data paths are hardcoded to assume a working directory within src (eg ../data/downloads/x. Eventually, we should move this into a variable that can be set, allowing us to treat the code in src as a package and move data_pipeline.py outside of src, to treat it as a script calling a package.
- [x] Rename the repo from `hourly-egrid`

**Comment by grgmiller** [comment]
@miloknowles @gailin-p based on some of my work on the `emission-factors` repository with @burkaman Jeff, I'm realizing that it may be useful to package the OGE repository so that we can import and use some of the same functions, tables, and variables from the OGE pipeline in other places. 

However, I don't have a lot of experience packaging repositories. My questions for you are:
1. Do we need to package OGE to make it callable in our other repos? Or could we just pip install it in the local environment using the git url (like we're [already doing](https://github.com/singularity-energy/open-grid-emissions/blob/bce51f798070b1773224c8b662c695bb77b47080/environment.yml#L31) with pudl and gridemissions)?
2. What would be the advantages to packaging OGE? Disadvantages?
3. How big of a lift do you think it would be to make OGE a package or library?

**Comment by burkaman** [comment]
I think the main advantage to packaging would be to make it more usable for people outside Singularity, if we think this would be of interest to other people. And I guess the associated disadvantage there would be an increased maintenance burden for us if we're managing an actively used library. In order to pip install directly from GitHub I think you still have to do the work to package-ify it, and since this is a public repo if we've already done that work I don't see any reason not to publish it to PyPI.

I'm not sure how much effort it would be, you can look at our [Singularity SDK](https://github.com/singularity-energy/singularity-energy-python-sdk) for a simple example of another public package we have. It's not too much overhead, but I'm not familiar enough with the codebase here to know how much restructuring would be necessary.

**Comment by grgmiller** [comment]
So some additional to-dos I'm realizing after attempting to package:
- [ ] The functions in `src.filepaths` work differently when using a packaged version verses when just using the library locally. Specifically, the relative filepath to the top directory will be different in each case.
- [ ] We may need to move all of the manual data from the data directory into the src directory so that it is included with the package.

**Comment by grgmiller** [comment]
Addressed by #323 and #324
